---
name: Rust linting
on:
  pull_request:
    paths:
      - .github/workflows/*.yml
      - '**/*.rs'
  workflow_dispatch:

jobs:
  clippy-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install latest stable Rust
        run: rustup update stable

      - name: Clippy check
        env:
          RUSTFLAGS: --deny warnings
        run: |
          cargo clippy --locked --all-targets --no-default-features
          cargo clippy --locked --all-targets --all-features
